name: Run Jenkins Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  jenkins-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hinata-ui

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: sbitio/trigger-jenkins-job@master
        with:
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
          JENKINS_HOST: ${{ secrets.JENKINS_HOST }}
          JENKINS_JOB: ${{ secrets.JENKINS_JOB }}
